# Generated by Django 2.1.5 on 2019-03-09 09:42

import core.db_index
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.URLField(db_index=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('parent_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenreMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.URLField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('laconic_description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TropeTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TropeTagMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('trope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trope')),
                ('trope_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TropeTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TropeTrope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_trope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trope')),
                ('to_trope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by_tropes', to='core.Trope')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TropeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('snippet', models.TextField(default=None, null=True)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('is_ymmv', models.BooleanField(default=False)),
                ('trope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trope')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('url', models.URLField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Creator')),
                ('genres', models.ManyToManyField(through='core.GenreMap', to='core.Genre')),
                ('tropes', models.ManyToManyField(through='core.TropeWork', to='core.Trope')),
            ],
        ),
        migrations.AddField(
            model_name='tropework',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Work'),
        ),
        migrations.AddField(
            model_name='trope',
            name='referenced_tropes',
            field=models.ManyToManyField(through='core.TropeTrope', to='core.Trope'),
        ),
        migrations.AddField(
            model_name='trope',
            name='tags',
            field=models.ManyToManyField(through='core.TropeTagMap', to='core.TropeTag'),
        ),
        migrations.AddField(
            model_name='genremap',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Work'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=core.db_index.GistIndexTrigrams(fields=['name'], name='core_work_name_8abedd_gist'),
        ),
    ]
